version: 2.1

executors:
  node-executor:
    docker:
      - image: node:18

jobs:
  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Create env
          command: |
            touch .env
            echo $prod > .env
      
      - run:
          name: Listing project file
          command: |
              ls -la
              echo "Current user: $(whoami)"

      - run:
          name: Transfer project files
          command: |  
            scp -o StrictHostKeyChecking=no -r ./* $user@$instance_ip:/home/ubuntu/develop/
      - run:
          name: Install dependencies
          command: |  
            ssh -o StrictHostKeyChecking=no $user@$instance_ip "cd /home/ubuntu/develop/ && npm ci"
      - run:
          name: Build project
          command: |  
            ssh -o StrictHostKeyChecking=no $user@$instance_ip "cd /home/ubuntu/develop/ && npm run build"
            ssh -o StrictHostKeyChecking=no $user@$instance_ip "cd /home/ubuntu/develop/ && pm2 restart 0"
      - run:
          name: Execute remote commands
          command: |
            ssh -o StrictHostKeyChecking=no $user@$instance_ip "echo 'pipeline completed'"
            # ssh -o StrictHostKeyChecking=no $user@$instance_ip "bash /home/ubuntu/pot.sh > ~/develop/test.txt"
            ssh -o StrictHostKeyChecking=no $user@$instance_ip "sudo netstat -tnlp > ~/develop/netstat_.txt"
      - run:
          name: Cleanup
          command: echo "Build and deployment completed successfully for the React App. Cleaning up..."

workflows:
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
