version: 2.1

executors:
  node-executor:
    docker:
      - image: node:18

jobs:
  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Transfer build files
          command: |
            scp -o StrictHostKeyChecking=no -r build $user@$instance_ip:/var/www/html/strapi/
      - run:
          name: Execute remote commands
          command: |
            ssh -o StrictHostKeyChecking=no $user@$instance_ip "echo 'pipeline completed'"
            # ssh -o StrictHostKeyChecking=no $user@$instance_ip "bash /home/ubuntu/pot.sh > ~/develop/test.txt"
            ssh -o StrictHostKeyChecking=no $user@$instance_ip "sudo netstat -tnlp > ~/develop/netstat_.txt"
      - run:
          name: Cleanup
          command: echo "Build and deployment completed successfully for the React App. Cleaning up..."

workflows:
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
